data:
  batch_size: 16
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: ""
  num_workers: 4
  pin_mem: true
  root_path: /datasets/imagenet-object-localization-challenge/ILSVRC/Data/CLS-LOC
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false  
  train_fraction: 0.001
logging:
  folder: /users/kutay.eroglu/logs/ijepa/pretraining
  write_tag: jepa_green
mask:
  mask_type: multigreen
  green_noise_data_path: /users/kutay.eroglu/datasets/green_noise_data_3072.npz
  allow_overlap: false
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 1
  patch_size: 16
  pred_mask_scale:
  - 0.6
  - 0.8
  aspect_ratio:
  - 0.75
  - 1.5
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_huge
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04

